name: Snake-Grid-Animation

on:
  # run automatically every 6 hours
  schedule:
    - cron: "0 0 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  #push:
  #  branches:
  #  - main

jobs:
  generate-snake-grid-animation:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate snake-grid-animation svgs
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake-grid-animation.svg
            dist/github-snake-grid-dark-animation.svg?palette=github-dark
            dist/github-snake-grid-custom-animation.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push snake-grid-animation svgs
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: snake-grid-animations
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
